### ISSUE TITLE
Do you need index?

### ISSUE THREAD

**Issue by NC-MXTC** [rodrigozavala/NCTaskManager#3]
https://github.com/rodrigozavala/NCTaskManager/blob/a3172b0fd70c88402fc8358d193f38f5f87d0220/src/main/java/mx/tc/j2se/tasks/LinkedTaskListImpl.java#L160

I see it is to assign a number to each node, but you have to go through all the trouble of re-indexing every time you add or remove, but in the end in getTask you still have to go through each node one by one checking the index. Is it an essential property?

**Comment by rodrigozavala** [comment]
No, sorry, I forgot to erase it
