### ISSUE TITLE
Loop through map entries

### ISSUE THREAD

**Issue by NC-MXTC** [rodrigozavala/NCTaskManager#5]
https://github.com/rodrigozavala/NCTaskManager/blob/085c6f3371c7efe65ef0119da85fb9310b854ab2/src/main/java/mx/tc/j2se/tasks/Tasks.java#L65-L69

https://github.com/rodrigozavala/NCTaskManager/blob/085c6f3371c7efe65ef0119da85fb9310b854ab2/src/main/java/mx/tc/j2se/tasks/Tasks.java#L79-L83

You loop through the whole map to get the value of a certain key when you already know the key? Check the `get()` method in Map

**Comment by rodrigozavala** [comment]
Thanks, now it uses map.get(i).add(t)

**Comment by rodrigozavala** [comment]
.
